Repository softeerbootcamp-2nd/ios-keynote, pull requests merged in 2023-07, with the labels that each got.

#1 [배남석] 아이패드 앱 프로젝트
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyKeynote/MyKeynote/App/AppDelegate.swift
  MyKeynote/MyKeynote/App/Assets.xcassets/AccentColor.colorset/Contents.json
  MyKeynote/MyKeynote/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyKeynote/MyKeynote/App/Assets.xcassets/Contents.json
  MyKeynote/MyKeynote/App/Base.lproj/LaunchScreen.storyboard
  MyKeynote/MyKeynote/App/Info.plist
  MyKeynote/MyKeynote/App/SceneDelegate.swift
  MyKeynote/MyKeynote/Model/Class/Color.swift
  MyKeynote/MyKeynote/Model/Class/Factory.swift
  MyKeynote/MyKeynote/Model/Class/ImageSlide.swift
  MyKeynote/MyKeynote/Model/Class/Slide.swift
  MyKeynote/MyKeynote/Model/Class/SquareSlide.swift
  MyKeynote/MyKeynote/Model/Protocol/RandomValueCreator.swift
  MyKeynote/MyKeynote/ViewController/ViewController.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITestsLaunchTests.swift
  README.md
Labels: step3-1

#2 [조승기] 아이패드 앱 프로젝트
  .DS_Store
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyKeynote/MyKeynote/App/AppDelegate.swift
  MyKeynote/MyKeynote/App/Assets.xcassets/AccentColor.colorset/Contents.json
  MyKeynote/MyKeynote/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyKeynote/MyKeynote/App/Assets.xcassets/Contents.json
  MyKeynote/MyKeynote/App/Base.lproj/LaunchScreen.storyboard
  MyKeynote/MyKeynote/App/SceneDelegate.swift
  MyKeynote/MyKeynote/Info.plist
  MyKeynote/MyKeynote/Model/Rect.swift
  MyKeynote/MyKeynote/Model/RectFactory.swift
  MyKeynote/MyKeynote/Model/SKColor.swift
  MyKeynote/MyKeynote/Model/Square.swift
  MyKeynote/MyKeynote/Util/IDService.swift
  MyKeynote/MyKeynote/Util/IDServiceProtocol.swift
  MyKeynote/MyKeynote/Util/Logger+.swift
  MyKeynote/MyKeynote/Util/OneToTen.swift
  MyKeynote/MyKeynote/ViewController/KeyNoteViewController.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITestsLaunchTests.swift
  README.md
Labels: step3-1

#3 [오승민] Slide 모델 구현 및 Factory 구현
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyKeynote/MyKeynote/App/AppDelegate.swift
  MyKeynote/MyKeynote/App/SceneDelegate.swift
  MyKeynote/MyKeynote/Controller/ViewController.swift
  MyKeynote/MyKeynote/Model/DataModel/SMAlpha.swift
  MyKeynote/MyKeynote/Model/DataModel/SMColor.swift
  MyKeynote/MyKeynote/Model/DataModel/SMSize.swift
  MyKeynote/MyKeynote/Model/DataModel/SMUUID.swift
  MyKeynote/MyKeynote/Model/Slide/RectangleSlide.swift
  MyKeynote/MyKeynote/Model/Slide/Slide.swift
  MyKeynote/MyKeynote/Model/Slide/SlideFactory.swift
  MyKeynote/MyKeynote/Model/Slide/SquareSlide.swift
  MyKeynote/MyKeynote/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  MyKeynote/MyKeynote/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyKeynote/MyKeynote/Resource/Assets.xcassets/Contents.json
  MyKeynote/MyKeynote/Resource/Base.lproj/LaunchScreen.storyboard
  MyKeynote/MyKeynote/Resource/Info.plist
  MyKeynote/MyKeynote/Util/Logger+Extension.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITestsLaunchTests.swift
  README.md
Labels: step3-1

#4 [이수민] W3-1 아이패드 앱 프로젝트
  .DS_Store
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyKeynote/MyKeynote/AppDelegate.swift
  MyKeynote/MyKeynote/Assets.xcassets/AccentColor.colorset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/Contents.json
  MyKeynote/MyKeynote/Base.lproj/LaunchScreen.storyboard
  MyKeynote/MyKeynote/Info.plist
  MyKeynote/MyKeynote/MainViewController.swift
  MyKeynote/MyKeynote/Model/AlphaType.swift
  MyKeynote/MyKeynote/Model/Factory.swift
  MyKeynote/MyKeynote/Model/Protocols.swift
  MyKeynote/MyKeynote/Model/RGBColor.swift
  MyKeynote/MyKeynote/Model/SquareSlide.swift
  MyKeynote/MyKeynote/SceneDelegate.swift
  MyKeynote/MyKeynote/StringExtension.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITestsLaunchTests.swift
  README.md
Labels: step3-1

#5 [변상연] 아이패드 앱 프로젝트 구현
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyKeynote/MyKeynote/Info.plist
  MyKeynote/MyKeynote/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  MyKeynote/MyKeynote/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyKeynote/MyKeynote/Resource/Assets.xcassets/Contents.json
  MyKeynote/MyKeynote/Resource/Base.lproj/LaunchScreen.storyboard
  MyKeynote/MyKeynote/Source/App/AppDelegate.swift
  MyKeynote/MyKeynote/Source/App/SceneDelegate.swift
  MyKeynote/MyKeynote/Source/Model/Alpha.swift
  MyKeynote/MyKeynote/Source/Model/Point.swift
  MyKeynote/MyKeynote/Source/Model/Protocol/Slide.swift
  MyKeynote/MyKeynote/Source/Model/Protocol/SlideCreatable.swift
  MyKeynote/MyKeynote/Source/Model/RGB.swift
  MyKeynote/MyKeynote/Source/Model/RGBValue.swift
  MyKeynote/MyKeynote/Source/Model/SlideFactory.swift
  MyKeynote/MyKeynote/Source/Model/SlideID.swift
  MyKeynote/MyKeynote/Source/Model/SquareSlide.swift
  MyKeynote/MyKeynote/Source/ViewController/KeynoteViewController.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITestsLaunchTests.swift
Labels: step3-1

#6 [고정민] - (3-1) 아이패드 앱 프로젝트
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyKeynote/MyKeynote/AppDelegate.swift
  MyKeynote/MyKeynote/Assets.xcassets/AccentColor.colorset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/Contents.json
  MyKeynote/MyKeynote/Base.lproj/LaunchScreen.storyboard
  MyKeynote/MyKeynote/Base.lproj/Main.storyboard
  MyKeynote/MyKeynote/Info.plist
  MyKeynote/MyKeynote/Model/AlphaLevel.swift
  MyKeynote/MyKeynote/Model/AnimationApplicable.swift
  MyKeynote/MyKeynote/Model/IDGenerator.swift
  MyKeynote/MyKeynote/Model/Slide.swift
  MyKeynote/MyKeynote/Model/SlideContentManageable.swift
  MyKeynote/MyKeynote/Model/SlideDisplayable.swift
  MyKeynote/MyKeynote/Model/SlideElement.swift
  MyKeynote/MyKeynote/Model/SlideFactory.swift
  MyKeynote/MyKeynote/Model/SlideRGBColor.swift
  MyKeynote/MyKeynote/Model/SquareSlide.swift
  MyKeynote/MyKeynote/SceneDelegate.swift
  MyKeynote/MyKeynote/ViewController.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITestsLaunchTests.swift
  README.md
Labels: step3-1

#7 [정도현] 아이패드 앱 프로젝트 만들기
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyKeynote/MyKeynote/AppDelegate.swift
  MyKeynote/MyKeynote/Assets.xcassets/AccentColor.colorset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/Contents.json
  MyKeynote/MyKeynote/Base.lproj/LaunchScreen.storyboard
  MyKeynote/MyKeynote/Controller/MainViewController.swift
  MyKeynote/MyKeynote/Info.plist
  MyKeynote/MyKeynote/Model/Alpha.swift
  MyKeynote/MyKeynote/Model/BaseSlide.swift
  MyKeynote/MyKeynote/Model/KeynoteLogger.swift
  MyKeynote/MyKeynote/Model/RandomStringGenerator.swift
  MyKeynote/MyKeynote/Model/RectangleSlide.swift
  MyKeynote/MyKeynote/Model/SlideColor.swift
  MyKeynote/MyKeynote/Model/SlideFactory.swift
  MyKeynote/MyKeynote/Model/SlideFactoryProtocol.swift
  MyKeynote/MyKeynote/Model/SlideUUID.swift
  MyKeynote/MyKeynote/Model/SquareSlide.swift
  MyKeynote/MyKeynote/SceneDelegate.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITestsLaunchTests.swift
Labels: step3-1

#9 [양승현] 아이패드 앱 프로젝트 미션 1 구현
  .gitignore
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MyKeynote/MyKeynote.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITestsLaunchTests.swift
  MyKeynote/Source/Common/Extension/String+.swift
  MyKeynote/Source/Common/Extension/UIView+.swift
  MyKeynote/Source/Common/Extension/UInt32+.swift
  MyKeynote/Source/Common/Model/AppSetting.swift
  MyKeynote/Source/Common/Protocol/ConvenienceInit.swift
  MyKeynote/Source/Common/Protocol/LayoutSupport.swift
  MyKeynote/Source/Module/Keynote/Factory/RectModelAbstractFactory.swift
  MyKeynote/Source/Module/Keynote/Factory/SlideViewAbstractFactory.swift
  MyKeynote/Source/Module/Keynote/Model/AlphaModel.swift
  MyKeynote/Source/Module/Keynote/Model/GrayscaleRange.swift
  MyKeynote/Source/Module/Keynote/Model/RGBAModel.swift
  MyKeynote/Source/Module/Keynote/Model/RectModel.swift
  MyKeynote/Source/Module/Keynote/Model/RectModelFactory.swift
  MyKeynote/Source/Module/Keynote/View/KeynoteView.swift
  MyKeynote/Source/Module/Keynote/ViewController/KeynoteViewController.swift
  MyKeynote/Source/Module/RandomGenerator/Model/AlphaRandomGenerator.swift
  MyKeynote/Source/Module/RandomGenerator/Model/AlphabetRandomGenerator.swift
  MyKeynote/Source/Module/RandomGenerator/Model/NumberRandomGenerator.swift
  MyKeynote/Source/Module/RandomGenerator/Model/RGBRandomGenerator.swift
  MyKeynote/Source/Module/RandomGenerator/Model/UniqueIdRandomGenerator.swift
  MyKeynote/Source/Module/RandomGenerator/Model/UniqueIdRandomGeneratorStorage.swift
  MyKeynote/Source/Module/RandomGenerator/Protocol/RandomGeneratable.swift
  MyKeynote/Source/Module/RandomGenerator/Protocol/UniqueIdRandomGeneratorStorageProtocol.swift
  MyKeynote/Source/Support/AppDelegate.swift
  MyKeynote/Source/Support/Assets.xcassets/AccentColor.colorset/Contents.json
  MyKeynote/Source/Support/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyKeynote/Source/Support/Assets.xcassets/Contents.json
  MyKeynote/Source/Support/Base.lproj/LaunchScreen.storyboard
  MyKeynote/Source/Support/Info.plist
  MyKeynote/Source/Support/SceneDelegate.swift
  README.md
Labels: step3-1

#10 [배남석] 속성 변경 동작
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/App/SceneDelegate.swift
  MyKeynote/MyKeynote/Model/Class/Factory.swift
  MyKeynote/MyKeynote/Model/Class/Slide.swift
  MyKeynote/MyKeynote/Model/Class/SlideColor.swift
  MyKeynote/MyKeynote/Model/Class/SquareSlide.swift
  MyKeynote/MyKeynote/Model/Protocol/RandomValueCreator.swift
  MyKeynote/MyKeynote/Model/Struct/SlideManager.swift
  MyKeynote/MyKeynote/Util/Extension/CALayer+.swift
  MyKeynote/MyKeynote/Util/Extension/UIColor+.swift
  MyKeynote/MyKeynote/View/ColorView.swift
  MyKeynote/MyKeynote/View/ControlTitleLabel.swift
  MyKeynote/MyKeynote/View/PaddingLabel.swift
  MyKeynote/MyKeynote/View/SlideView.swift
  MyKeynote/MyKeynote/View/SquareView.swift
  MyKeynote/MyKeynote/ViewController/ViewController.swift
Labels: step3-2

#11 [조승기] 속성 변경 동작
  .DS_Store
  MyKeynote/.DS_Store
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/.DS_Store
  MyKeynote/MyKeynote/App/SceneDelegate.swift
  MyKeynote/MyKeynote/Model/.DS_Store
  MyKeynote/MyKeynote/Model/Colorful.swift
  MyKeynote/MyKeynote/Model/Rect.swift
  MyKeynote/MyKeynote/Model/RectFactory.swift
  MyKeynote/MyKeynote/Model/RectFactoryProtocol.swift
  MyKeynote/MyKeynote/Model/Rectable.swift
  MyKeynote/MyKeynote/Model/SKColor.swift
  MyKeynote/MyKeynote/Model/SKPoint.swift
  MyKeynote/MyKeynote/Model/SlideManager.swift
  MyKeynote/MyKeynote/Model/SlideManagerProtocol.swift
  MyKeynote/MyKeynote/Model/Square.swift
  MyKeynote/MyKeynote/Util/IDService.swift
  MyKeynote/MyKeynote/Util/OneToTen.swift
  MyKeynote/MyKeynote/Util/UIColor+.swift
  MyKeynote/MyKeynote/Util/UIView+.swift
  MyKeynote/MyKeynote/View/AlphaControlView.swift
  MyKeynote/MyKeynote/View/ColorControlView.swift
  MyKeynote/MyKeynote/View/ControlStackView.swift
  MyKeynote/MyKeynote/ViewController/KeyNoteViewController.swift
  MyKeynote/MyKeynoteTests/MockRectFactory.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
  MyKeynote/MyKeynoteTests/SlideManagerTest.swift
  README.md
Labels: step3-2

#12 관찰자(Observer) 패턴
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/Model/Class/Factory.swift
  MyKeynote/MyKeynote/Model/Class/ImageSlide.swift
  MyKeynote/MyKeynote/Model/Class/Slide.swift
  MyKeynote/MyKeynote/Model/Class/SlideAlpha.swift
  MyKeynote/MyKeynote/Model/Class/SlideColor.swift
  MyKeynote/MyKeynote/Model/Class/SlideIdentifier.swift
  MyKeynote/MyKeynote/Model/Class/SquareSlide.swift
  MyKeynote/MyKeynote/Model/Struct/DefaultSlideManager.swift
  MyKeynote/MyKeynote/Model/Struct/SlideManager.swift
  MyKeynote/MyKeynote/Util/Extension/NotificiationName+.swift
  MyKeynote/MyKeynote/Util/Extension/UIColor+.swift
  MyKeynote/MyKeynote/View/SlideView.swift
  MyKeynote/MyKeynote/ViewController/ViewController.swift
  MyKeynote/MyKeynoteTests/Mock/MockFactory.swift
  MyKeynote/MyKeynoteTests/Mock/MockSlideManager.swift
  MyKeynote/MyKeynoteTests/Tests/MyKeynoteSlideManagerTests.swift
  MyKeynote/MyKeynoteTests/Tests/MyKeynoteTests.swift
  README.md
Labels: step3-3

#13 [변상연] 속성 변경 기능 구현
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/Source/App/SceneDelegate.swift
  MyKeynote/MyKeynote/Source/Model/Point.swift
  MyKeynote/MyKeynote/Source/Model/Protocol/Slide.swift
  MyKeynote/MyKeynote/Source/Model/Protocol/SlideCreatable.swift
  MyKeynote/MyKeynote/Source/Model/Protocol/SlideManageable.swift
  MyKeynote/MyKeynote/Source/Model/RGB.swift
  MyKeynote/MyKeynote/Source/Model/Slide/Property/RGBColor.swift
  MyKeynote/MyKeynote/Source/Model/Slide/Property/RGBValue.swift
  MyKeynote/MyKeynote/Source/Model/Slide/Property/SYAlpha.swift
  MyKeynote/MyKeynote/Source/Model/Slide/Property/SYSize.swift
  MyKeynote/MyKeynote/Source/Model/Slide/Slide.swift
  MyKeynote/MyKeynote/Source/Model/Slide/SlideFactory.swift
  MyKeynote/MyKeynote/Source/Model/Slide/SlideID.swift
  MyKeynote/MyKeynote/Source/Model/Slide/SlideManager.swift
  MyKeynote/MyKeynote/Source/Model/Slide/SquareSlide.swift
  MyKeynote/MyKeynote/Source/Model/SlideFactory.swift
  MyKeynote/MyKeynote/Source/Model/SquareSlide.swift
  MyKeynote/MyKeynote/Source/Utils/Extension/UIColor+.swift
  MyKeynote/MyKeynote/Source/View/AlphaSettingView.swift
  MyKeynote/MyKeynote/Source/View/ColorSettingView.swift
  MyKeynote/MyKeynote/Source/View/KeynoteView.swift
  MyKeynote/MyKeynote/Source/View/PropertySideBarView.swift
  MyKeynote/MyKeynote/Source/View/SlideView.swift
  MyKeynote/MyKeynote/Source/View/SubSlideView.swift
  MyKeynote/MyKeynote/Source/ViewController/KeynoteViewController.swift
  MyKeynote/MyKeynoteTests/SildeManagerTests.swift
Labels: step3-2

#14 [오승민] 속성 변경 동작 & 관찰자(Observer)패턴
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote.xcodeproj/xcshareddata/xcschemes/MyKeynote.xcscheme
  MyKeynote/MyKeynote/Controller/ViewController.swift
  MyKeynote/MyKeynote/Model/DataModel/SMAlpha.swift
  MyKeynote/MyKeynote/Model/DataModel/SMColor.swift
  MyKeynote/MyKeynote/Model/DataModel/SMSize.swift
  MyKeynote/MyKeynote/Model/DataModel/SMUUID.swift
  MyKeynote/MyKeynote/Model/Slide/RectangleSlide.swift
  MyKeynote/MyKeynote/Model/Slide/Slide.swift
  MyKeynote/MyKeynote/Model/Slide/SlideFactory.swift
  MyKeynote/MyKeynote/Model/Slide/SlideManager.swift
  MyKeynote/MyKeynote/Model/Slide/SquareSlide.swift
  MyKeynote/MyKeynote/Model/SlideContent/SlideContent.swift
  MyKeynote/MyKeynote/Model/SlideContent/SlideContentFactory.swift
  MyKeynote/MyKeynote/Model/SlideContent/SquareContent.swift
  MyKeynote/MyKeynote/Util/Logger+Extension.swift
  MyKeynote/MyKeynote/Util/SMAlpha+CGFloat.swift
  MyKeynote/MyKeynote/Util/SMColor+UIColor.swift
  MyKeynote/MyKeynote/Util/SMSize+CGSize.swift
  MyKeynote/MyKeynote/Util/UIColor+Extension.swift
  MyKeynote/MyKeynote/View/MainLayout/Inspector/BackgroundColorChangeableButton.swift
  MyKeynote/MyKeynote/View/MainLayout/Inspector/InspectorView.swift
  MyKeynote/MyKeynote/View/MainLayout/Inspector/ValuePresentableStepper.swift
  MyKeynote/MyKeynote/View/MainLayout/LayoutConfigurable.swift
  MyKeynote/MyKeynote/View/MainLayout/MainView.swift
  MyKeynote/MyKeynote/View/MainLayout/NavigatorView.swift
  MyKeynote/MyKeynote/View/SlideView/ContentViewProtocol.swift
  MyKeynote/MyKeynote/View/SlideView/SlideView.swift
  MyKeynote/MyKeynote/View/SlideView/SquareContentView.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
  MyKeynote/MyKeynoteTests/SlideManagerTests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITests.swift
  MyKeynote/MyKeynoteUITests/MyKeynoteUITestsLaunchTests.swift
  README.md
Labels: step3-2, step3-3

#15 [고정민] - (3-2) 속성 변경 동작
  .DS_Store
  MyKeynote/.DS_Store
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/Base.lproj/Main.storyboard
  MyKeynote/MyKeynote/Component/BaseComponentView.swift
  MyKeynote/MyKeynote/Component/CustomStepperButton.swift
  MyKeynote/MyKeynote/Component/RectangleComponentView.swift
  MyKeynote/MyKeynote/DI/CompositionRoot.swift
  MyKeynote/MyKeynote/Extension/UIColor.swift
  MyKeynote/MyKeynote/Info.plist
  MyKeynote/MyKeynote/KeynoteViewController.swift
  MyKeynote/MyKeynote/Model/AlphaLevel.swift
  MyKeynote/MyKeynote/Model/AnimationApplicable.swift
  MyKeynote/MyKeynote/Model/Draggable.swift
  MyKeynote/MyKeynote/Model/Element/BaseElement.swift
  MyKeynote/MyKeynote/Model/Element/RectangleElement.swift
  MyKeynote/MyKeynote/Model/Element/SlideElementProtocol.swift
  MyKeynote/MyKeynote/Model/Factory/ComponentFactory.swift
  MyKeynote/MyKeynote/Model/Factory/ElementCollection.swift
  MyKeynote/MyKeynote/Model/Factory/SlideFactory.swift
  MyKeynote/MyKeynote/Model/Manager/SlideDataSource.swift
  MyKeynote/MyKeynote/Model/Manager/SlideManager.swift
  MyKeynote/MyKeynote/Model/Order.swift
  MyKeynote/MyKeynote/Model/Resizable.swift
  MyKeynote/MyKeynote/Model/Selectable.swift
  MyKeynote/MyKeynote/Model/Slide.swift
  MyKeynote/MyKeynote/Model/Slide/BaseSlide.swift
  MyKeynote/MyKeynote/Model/Slide/SlideListView.swift
  MyKeynote/MyKeynote/Model/Slide/SlideProtocol.swift
  MyKeynote/MyKeynote/Model/SlideCollection.swift
  MyKeynote/MyKeynote/Model/SlideContentManageable.swift
  MyKeynote/MyKeynote/Model/SlideRGBColor.swift
  MyKeynote/MyKeynote/Model/SquareSlide.swift
  MyKeynote/MyKeynote/SceneDelegate.swift
  MyKeynote/MyKeynote/View/InspectorView.swift
  MyKeynote/MyKeynote/View/KeynoteView.swift
  MyKeynote/MyKeynote/View/PresentationView.swift
  MyKeynote/MyKeynote/ViewController.swift
  MyKeynote/MyKeynoteTests/Mock/MockComponentFactory.swift
  MyKeynote/MyKeynoteTests/Mock/MockSlideFactory.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
Labels: step3-2

#16 [이수민] W3-2 속성 변경하기
  .DS_Store
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/App/AppDelegate.swift
  MyKeynote/MyKeynote/App/SceneDelegate.swift
  MyKeynote/MyKeynote/Assets.xcassets/SideViewColor.colorset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/SubViewColor.colorset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/SuperViewColor.colorset/Contents.json
  MyKeynote/MyKeynote/MainViewController.swift
  MyKeynote/MyKeynote/Model/AlphaType.swift
  MyKeynote/MyKeynote/Model/Content/ContentType.swift
  MyKeynote/MyKeynote/Model/Content/Contentable.swift
  MyKeynote/MyKeynote/Model/Content/ImageContent.swift
  MyKeynote/MyKeynote/Model/Content/SquareContent.swift
  MyKeynote/MyKeynote/Model/Factory.swift
  MyKeynote/MyKeynote/Model/Manage/SlideFactory.swift
  MyKeynote/MyKeynote/Model/Manage/SlideFactoryProducer.swift
  MyKeynote/MyKeynote/Model/Manage/SlideManager.swift
  MyKeynote/MyKeynote/Model/Protocols.swift
  MyKeynote/MyKeynote/Model/RGBColor.swift
  MyKeynote/MyKeynote/Model/Slide/ImageSlide.swift
  MyKeynote/MyKeynote/Model/Slide/Slidable.swift
  MyKeynote/MyKeynote/Model/Slide/SquareSlide.swift
  MyKeynote/MyKeynote/Model/SquareSlide.swift
  MyKeynote/MyKeynote/Model/Type/AlphaType.swift
  MyKeynote/MyKeynote/Model/Type/RGBColor.swift
  MyKeynote/MyKeynote/Model/Util/ConstantSize.swift
  MyKeynote/MyKeynote/Model/Util/Extension.swift
  MyKeynote/MyKeynote/StringExtension.swift
  MyKeynote/MyKeynote/View/ContentView/ContentViewFactory.swift
  MyKeynote/MyKeynote/View/ContentView/ImageContentView.swift
  MyKeynote/MyKeynote/View/ContentView/SquareContentView.swift
  MyKeynote/MyKeynote/View/MainView/MainView.swift
  MyKeynote/MyKeynote/View/MainView/SlideView.swift
  MyKeynote/MyKeynote/View/SideView/ContentPropertyView.swift
  MyKeynote/MyKeynote/View/SideView/SideView.swift
  MyKeynote/MyKeynote/View/SideView/SlideListView.swift
  MyKeynote/MyKeynote/ViewController/MainViewController.swift
  MyKeynote/MyKeynoteTests/MyKeynoteTests.swift
Labels: step3-2

#18 [배남석] 슬라이드 목록 표시
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/Model/Class/Slide.swift
  MyKeynote/MyKeynote/Model/Class/SlideAlpha.swift
  MyKeynote/MyKeynote/Model/Protocol/RandomValueCreator.swift
  MyKeynote/MyKeynote/Model/Struct/DefaultSlideManager.swift
  MyKeynote/MyKeynote/Util/Extension/CALayer+.swift
  MyKeynote/MyKeynote/Util/Extension/UIColor+.swift
  MyKeynote/MyKeynote/View/InspectorView.swift
  MyKeynote/MyKeynote/View/SlideListCell.swift
  MyKeynote/MyKeynote/View/SlideView.swift
  MyKeynote/MyKeynote/ViewController/ViewController.swift
  MyKeynote/MyKeynoteTests/Mock/MockSlideManager.swift
  MyKeynote/MyKeynoteTests/Tests/MyKeynoteSlideManagerTests.swift
  README.md
Labels: step3-4

#20 [고정민] - (3-3) 관찰자(Observer) 패턴
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/Component/BaseComponentView.swift
  MyKeynote/MyKeynote/DI/CompositionRoot.swift
  MyKeynote/MyKeynote/Extension/SlideRGBColor+.swift
  MyKeynote/MyKeynote/Extension/UIColor.swift
  MyKeynote/MyKeynote/KeynoteViewController.swift
  MyKeynote/MyKeynote/Model/Element/BaseElement.swift
  MyKeynote/MyKeynote/Model/Element/SlideElementProtocol.swift
  MyKeynote/MyKeynote/Model/Factory/ElementCollection.swift
  MyKeynote/MyKeynote/Model/Manager/SlideManager.swift
  MyKeynote/MyKeynote/Model/Notification/NotificationName.swift
  MyKeynote/MyKeynote/Model/Slide/BaseSlide.swift
  MyKeynote/MyKeynote/Model/SlideContentManageable.swift
  MyKeynote/MyKeynote/Model/SlideRGBColor.swift
  MyKeynote/MyKeynote/SceneDelegate.swift
  MyKeynote/MyKeynote/View/InspectorView.swift
  MyKeynote/MyKeynote/View/KeynoteView.swift
  MyKeynote/MyKeynote/View/PresentationView.swift
Labels: step3-3

#21 [정도현] 키노트 속성변경 + 관찰자 도입
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/ContainerViewController/KeynoteSplitViewController.swift
  MyKeynote/MyKeynote/Controller/InspectorViewController.swift
  MyKeynote/MyKeynote/Controller/KeynoteContainerViewController.swift
  MyKeynote/MyKeynote/Controller/MainViewController.swift
  MyKeynote/MyKeynote/Controller/NavigatorViewController.swift
  MyKeynote/MyKeynote/Controller/PresentingViewController.swift
  MyKeynote/MyKeynote/Controller/ShapeInspectViewPresenter.swift
  MyKeynote/MyKeynote/Factories/BaseSlideFactory.swift
  MyKeynote/MyKeynote/Factories/InspectorFactory.swift
  MyKeynote/MyKeynote/Factories/ShapeFactory.swift
  MyKeynote/MyKeynote/Factories/ShapeInfoFactory.swift
  MyKeynote/MyKeynote/Factories/SlideFactoryProtocol.swift
  MyKeynote/MyKeynote/Model/BaseComponent.swift
  MyKeynote/MyKeynote/Model/BaseSlide.swift
  MyKeynote/MyKeynote/Model/KeynoteLogger.swift
  MyKeynote/MyKeynote/Model/NotificationCenterConstant.swift
  MyKeynote/MyKeynote/Model/Properties/Alpha.swift
  MyKeynote/MyKeynote/Model/Properties/KeynoteColor.swift
  MyKeynote/MyKeynote/Model/Properties/keynoteUUID.swift
  MyKeynote/MyKeynote/Model/RectangleSlide.swift
  MyKeynote/MyKeynote/Model/Shape/ShapeInspector.swift
  MyKeynote/MyKeynote/Model/Shape/ShapeProtocols.swift
  MyKeynote/MyKeynote/Model/Shape/Square.swift
  MyKeynote/MyKeynote/Model/Shape/didChangeShapeComponent.swift
  MyKeynote/MyKeynote/Model/Slide/BaseSlide.swift
  MyKeynote/MyKeynote/Model/Slide/SlideManager.swift
  MyKeynote/MyKeynote/Model/Slide/SlideProtocols.swift
  MyKeynote/MyKeynote/Model/SlideFactory.swift
  MyKeynote/MyKeynote/Model/SquareSlide.swift
  MyKeynote/MyKeynote/SceneDelegate.swift
  MyKeynote/MyKeynote/UIColor + Extension.swift
  MyKeynote/MyKeynote/UIView + Extension.swift
  MyKeynote/MyKeynote/View/AlphaSettingView.swift
  MyKeynote/MyKeynote/View/ColorSettingView.swift
  MyKeynote/MyKeynote/View/ComponentEventDelegate.swift
  MyKeynote/MyKeynote/View/InspectViewFactory.swift
  MyKeynote/MyKeynote/View/InspectViewable.swift
  MyKeynote/MyKeynote/View/NavigatorView.swift
  MyKeynote/MyKeynote/View/ShapeView.swift
  MyKeynote/MyKeynote/View/SlideView.swift
  MyKeynote/MyKeynote/View/statusBarView.swift
Labels: step3-2, step3-3

#22 [오승민] 슬라이드 목록 표시
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote.xcodeproj/xcshareddata/xcschemes/MyKeynote.xcscheme
  MyKeynote/MyKeynote.xctestplan
  MyKeynote/MyKeynote/Controller/ViewController+FromModel.swift
  MyKeynote/MyKeynote/Controller/ViewController+FromView.swift
  MyKeynote/MyKeynote/Controller/ViewController.swift
  MyKeynote/MyKeynote/DataModel/SMAlpha.swift
  MyKeynote/MyKeynote/DataModel/SMColor.swift
  MyKeynote/MyKeynote/DataModel/SMSize.swift
  MyKeynote/MyKeynote/DataModel/SMUUID.swift
  MyKeynote/MyKeynote/Model/DataModel/SMSize.swift
  MyKeynote/MyKeynote/Model/Notification+Namespace.swift
  MyKeynote/MyKeynote/Model/Slide.swift
  MyKeynote/MyKeynote/Model/Slide/SlideManager.swift
  MyKeynote/MyKeynote/Model/SlideContent/SlideContent.swift
  MyKeynote/MyKeynote/Model/SlideContent/SlideContentFactory.swift
  MyKeynote/MyKeynote/Model/SlideContent/SquareContent.swift
  MyKeynote/MyKeynote/Model/SlideContentFactory/SlideContentFactory.swift
  MyKeynote/MyKeynote/Model/SlideContentFactory/SquareContentFactory.swift
  MyKeynote/MyKeynote/Model/SlideManager.swift
  MyKeynote/MyKeynote/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  MyKeynote/MyKeynote/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyKeynote/MyKeynote/Resources/Assets.xcassets/Contents.json
  MyKeynote/MyKeynote/Resources/Base.lproj/LaunchScreen.storyboard
  MyKeynote/MyKeynote/Resources/Info.plist
  MyKeynote/MyKeynote/Util/Logger+Extension.swift
  MyKeynote/MyKeynote/Util/SMAlpha+CGFloat.swift
  MyKeynote/MyKeynote/Util/SMColor+UIColor.swift
  MyKeynote/MyKeynote/Util/UIColor+Extension.swift
  MyKeynote/MyKeynote/View/LayoutConfigurable.swift
  MyKeynote/MyKeynote/View/MainLayout/Inspector/InspectorView.swift
  MyKeynote/MyKeynote/View/MainLayout/Inspector/ValuePresentableStepper.swift
  MyKeynote/MyKeynote/View/MainLayout/MainView.swift
  MyKeynote/MyKeynote/View/MainLayout/Navigator/NavigatorView.swift
  MyKeynote/MyKeynote/View/MainLayout/Navigator/SlideNavigatorTableViewCell.swift
  MyKeynote/MyKeynote/View/MainLayout/NavigatorView.swift
  MyKeynote/MyKeynote/View/SlideView/SlideContentView/ContentViewProtocol.swift
  MyKeynote/MyKeynote/View/SlideView/SlideContentView/SquareContentView.swift
  MyKeynote/MyKeynote/View/SlideView/SlideView.swift
  MyKeynote/MyKeynoteTests/SlideManagerTests.swift
  README.md
Labels: step3-4

#25 [변상연] 슬라이드 목록 표시
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/Source/Model/Protocol/SlideManageable.swift
  MyKeynote/MyKeynote/Source/View/KeynoteView.swift
  MyKeynote/MyKeynote/Source/View/SlideContentView.swift
  MyKeynote/MyKeynote/Source/View/SlideListSideBarView.swift
  MyKeynote/MyKeynote/Source/View/SlideListTableViewCell.swift
  MyKeynote/MyKeynote/Source/View/SlideView.swift
  MyKeynote/MyKeynote/Source/ViewController/KeynoteViewController.swift
Labels: step3-4

#28 [이수민] W3-3, W3-4 관찰자 패턴 및 슬라이드 목록 표시
  .DS_Store
  MyKeynote/MyKeynote.xcodeproj/project.pbxproj
  MyKeynote/MyKeynote/App/SceneDelegate.swift
  MyKeynote/MyKeynote/Assets.xcassets/CellImageColor.colorset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/InnerCellColor.colorset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/OuterCellColor.colorset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/SlideAddButtonColor.colorset/Contents.json
  MyKeynote/MyKeynote/Assets.xcassets/SlideAddButtonTextColor.colorset/Contents.json
  MyKeynote/MyKeynote/Model/Content/Contentable.swift
  MyKeynote/MyKeynote/Model/Content/ImageContent.swift
  MyKeynote/MyKeynote/Model/Content/SquareContent.swift
  MyKeynote/MyKeynote/Model/Manage/ContentType.swift
  MyKeynote/MyKeynote/Model/Manage/IDManager.swift
  MyKeynote/MyKeynote/Model/Manage/SlideFactory.swift
  MyKeynote/MyKeynote/Model/Manage/SlideFactoryProducer.swift
  MyKeynote/MyKeynote/Model/Manage/SlideManager.swift
  MyKeynote/MyKeynote/Model/Slide/ImageSlide.swift
  MyKeynote/MyKeynote/Model/Slide/Slidable.swift
  MyKeynote/MyKeynote/Model/Slide/SquareSlide.swift
  MyKeynote/MyKeynote/Model/Type/RGBColor.swift
  MyKeynote/MyKeynote/Model/Util/ConstantSize.swift
  MyKeynote/MyKeynote/Model/Util/Extension.swift
  MyKeynote/MyKeynote/Model/Util/StringExtension.swift
  MyKeynote/MyKeynote/Model/Util/UIColorExtension.swift
  MyKeynote/MyKeynote/View/ContentView/ContentViewFactory.swift
  MyKeynote/MyKeynote/View/ContentView/ImageContentView.swift
  MyKeynote/MyKeynote/View/ContentView/SquareContentView.swift
  MyKeynote/MyKeynote/View/MainView/MainView.swift
  MyKeynote/MyKeynote/View/MainView/SlideView.swift
  MyKeynote/MyKeynote/View/SideView/ContentPropertyView.swift
  MyKeynote/MyKeynote/View/SideView/CustomCell.swift
  MyKeynote/MyKeynote/View/SideView/SlideListView.swift
  MyKeynote/MyKeynote/ViewController/MainViewController.swift
Labels: step3-3, step3-4
